### ISSUE TITLE
Metabarlist

### ISSUE THREAD

**Issue by IreneGregori** [metabaRfactory/metabaR#39]
In order to create a metabarlist file, I must create 4 different files (motus, pcrs,..). 
How can I create those files starting from an Obitools3 output? In particullary, which files do I have to take from all the outputs made by Obitools3? 
Thank you

**Comment by celine-mercier** [comment]
Hi Irene, I looked into it, I think I can get something working for next Tuesday. It will be an `obi export` option to produce the files for `obifiles_to_metabarlist`. If you send me (celine.mercier@metabarcoding.org) your ngsfilter file, and your sample characteristics file if you have one, I can test it on them, but I can do without. Cheers

**Comment by celine-mercier** [comment]
Hi Irene,

Could you try sending me the files attached in a new email to celine.mercier.bioinfo@gmail.com, and not as a reply to this? I can't really see them like this.

Thanks! Cheers
