### ISSUE TITLE
Little Typo in Let's MetabaR! tutorial

### ISSUE THREAD

**Issue by LafontRapnouilTristan** [metabaRfactory/metabaR#51]
Hi,

I just notice a typo in the [removing spurious signal](https://metabarfactory.github.io/metabaR/articles/metabaRF-vignette.html#removing-spurious-signal) section of the official tutorial.

![image](https://user-images.githubusercontent.com/49724216/212757921-ae76816b-bccc-4651-b44e-634b2f15fc73.png)

It seems to me that the second row should use `rowSums` as `pcrs` are the rows of the reads matrix of the `metabarlist` object.

Cheers,
Tristan

**Comment by lionncle** [comment]
Hi, 

The typo was already corrected in one pull request which has not merge. It's done now ;)

Cheers,
Clément
